# Site settings
title: Luana Silva
description: >
  Tecnologia e programação.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Motaquillah Maddane
  googleplus: https://www.google.com/+MotaquillahMaddane
  github: Luana-silva
  twitter: 
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown